name: INDEX
on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout 
        uses: actions/checkout@v1
      - name: Use Hello
        uses: ./.github/actions/Hello
        id: hello
        with:
          who-to-greet: "World"
      - name: Output
        run: echo ${{steps.hello.outputs.time}}
      # - run: 
      #   echo " Time: ${{ steps.hello.outputs.time}} " 