name: INDEX
on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./github/actions/Hello
        id: hello
        with:
          who-to-greet: "World"
      - run: 
        echo " Time: ${{ steps.hello.outputs.time}} " 