name: ABC
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: ./github/actions/Hello
      #   id: hello
      #   with:
      #     who-to-greet: "World"
      - name : Log Env VAR
        run: |
          echo "Hi" 